"""empty message

Revision ID: 273e8b6fbed1
Revises: 43eb44d3be89
Create Date: 2026-08-10 11:00:22.103593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273e8b6fbed1'
down_revision = '43eb44d3be89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
